### ISSUE TITLE
升级内核后wlan0没有找到

### ISSUE THREAD

**Issue by gaohongbin** [chainsx/firmware64-rpi#1]
[root@k8s-master-1 kernel]# ifconfig
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 0.0.0.0
        ether 02:42:7b:9b:52:67  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.137.200  netmask 255.255.255.0  broadcast 192.168.137.255
        inet6 fe80::ba27:ebff:feaa:dae6  prefixlen 64  scopeid 0x20<link>
        ether b8:27:eb:aa:da:e6  txqueuelen 1000  (Ethernet)
        RX packets 87479  bytes 87441283 (83.3 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 80249  bytes 63383681 (60.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 132679  bytes 16241523 (15.4 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 132679  bytes 16241523 (15.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by railjty** [comment]
uname -a的输出？

**Comment by chainsx** [comment]
问题已经解决了
